version: '3.8'

services:
  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx:latest
    ports:
      - 80:80
      - 443:443
    volumes:
      - ~/prj:/var/www
      - ./cfg/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cfg/nginx/cert:/etc/nginx/cert
      - ./cfg/d.bashrc:/etc/bash.bashrc

  php56:
    hostname: php56
    container_name: php56
    build:
      context: ./cfg/php
      args:
        cont: "chialab/php-dev:5.6-fpm"
    volumes:
      - ~/prj:/var/www
      - ./cfg/d.bashrc:/etc/bash.bashrc
      - ./cfg/php/php.ini:/usr/local/etc/php/php.ini
      - ./cfg/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  php73:
    hostname: php73
    container_name: php73
    build:
      context: ./cfg/php
      args:
        cont: "chialab/php-dev:7.3-fpm"
    volumes:
      - ~/prj:/var/www
      - ./cfg/d.bashrc:/etc/bash.bashrc
      - ./cfg/php/php.ini:/usr/local/etc/php/php.ini
      - ./cfg/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  php74:
    hostname: php74
    container_name: php74
    build:
      context: ./cfg/php
      args:
        cont: "chialab/php-dev:7.4-fpm"
    volumes:
      - ~/prj:/var/www
      - ./cfg/d.bashrc:/etc/bash.bashrc
      - ./cfg/php/php.ini:/usr/local/etc/php/php.ini
      - ./cfg/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini

  db:
    hostname: db
    container_name: db
    image: mariadb
    # image: mysql
    # image: mysql5
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --sql_mode=ONLY_FULL_GROUP_BY
    ports:
      - 3306:3306
    volumes:
      - ./db/maria:/var/lib/mysql
      - ./cfg/d.bashrc:/etc/bash.bashrc
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

  dns:
    hostname: dns
    container_name: dns
    image: defreitas/dns-proxy-server
    ports:
      # - 8053:5380
      - 53:53/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
      - ./cfg/dns.json:/app/conf/config.json
      - ./cfg/d.bashrc:/etc/bash.bashrc
  
  mail:
    hostname: mail
    container_name: mail
    image: mailhog/mailhog
