version: '3.3'

volumes:
  www:
    # driver: local
    # driver_opts:
    #   type: none
    #   device: ~/prj
    #   o: bind
  db:
  # mysql:
  # mysql8:
  # mysql5:

services:
  ftp:
    hostname: ftp
    container_name: ftp
    image: wildscamp/vsftpd
    # restart: always
    volumes:
      - www:/home/virtual/ftp/www
      - ./cfg/d.bashrc:/root/.bashrc
    ports:
      - 127.0.0.1:21:21
      - 127.0.0.1:30000-30010:30000-30010
    environment:
      PASV_MIN_PORT: 30000
      PASV_MAX_PORT: 30010
      VSFTPD_USER_1: "ftp:secret:82:82"
  
  # sftp:
  #   hostname: sftp
  #   container_name: sftp
  #   image: atmoz/sftp:alpine
  #   # restart: always
  #   volumes:
  #     - www:/home/user/www
  #     - ./cfg/d.bashrc:/root/.bashrc
  #   ports:
  #       - 127.0.0.1:22:22
  #   command: user:secret:82:82

  dns:
    hostname: dns
    container_name: dns
    image: defreitas/dns-proxy-server
    # restart: always
    ports:
      # - 127.0.0.1:8053:5380
      - 127.0.0.1:53:53/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
      - ./cfg/dns.json:/app/conf/config.json
      - ./cfg/d.bashrc:/root/.bashrc

  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx
    # restart: always
    ports:
      - 127.0.0.1:80:80
      - 127.0.0.1:443:443
    volumes:
      - www:/var/www
      - ./cfg/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cfg/nginx/cert:/etc/nginx/cert
      - ./cfg/d.bashrc:/root/.bashrc

  php73:
    hostname: php73
    container_name: php73
    image: m0bua/php:7.3-fpm-alpine
    # restart: always
    volumes:
      - www:/var/www
      - ./cfg/d.bashrc:/root/.bashrc
      - ./cfg/php/php.ini:/usr/local/etc/php/php.ini
      - ./cfg/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # - ./cfg/ImageMagick-policy.xml:/etc/ImageMagick-6/policy.xml #debian based only

  php74d:
    hostname: php74d
    container_name: php74d
    image: m0bua/php:7.4-fpm-alpine-dev
    # restart: always
    volumes:
      - www:/var/www
      - ./cfg/d.bashrc:/root/.bashrc
      - ./cfg/php/php.ini:/usr/local/etc/php/php.ini
      - ./cfg/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # - ./cfg/ImageMagick-policy.xml:/etc/ImageMagick-6/policy.xml #debian based only

  php73d:
    hostname: php73d
    container_name: php73d
    image: m0bua/php:7.3-fpm-alpine-dev
    # restart: always
    volumes:
      - www:/var/www
      - ./cfg/d.bashrc:/root/.bashrc
      - ./cfg/php/php.ini:/usr/local/etc/php/php.ini
      - ./cfg/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # - ./cfg/ImageMagick-policy.xml:/etc/ImageMagick-6/policy.xml #debian based only

  php56d:
    hostname: php56d
    container_name: php56d
    image: m0bua/php:5.6-fpm-alpine-dev
    # restart: always
    volumes:
      - www:/var/www
      - ./cfg/d.bashrc:/root/.bashrc
      - ./cfg/php/php.ini:/usr/local/etc/php/php.ini
      - ./cfg/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # - ./cfg/ImageMagick-policy.xml:/etc/ImageMagick-6/policy.xml #debian based only

  db:
    hostname: db
    container_name: db
    image: mariadb
    # image: mysql
    # image: mysql:8
    # image: mysql:5
    # restart: always
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --sql_mode=ONLY_FULL_GROUP_BY
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./cfg/d.bashrc:/root/.bashrc
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
  
  mail:
    hostname: mail
    container_name: mail
    image: mailhog/mailhog
    # restart: always

  adminer:
    hostname: adminer
    container_name: adminer
    image: adminer
    # restart: always
