version: '3.8'

services:
  nginx:
    hostname: nginx
    container_name: nginx
    image: nginx
    # restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - www:/var/www
      - ./cfg/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./cfg/nginx/cert:/etc/nginx/cert
      - ./cfg/d.bashrc:/root/.bashrc

  php56:
    hostname: php56
    container_name: php56
    image: "m0bua/php:5.6-fpm-alpine-dev"
    # restart: always
    volumes:
      - www:/var/www
      - ./cfg/d.bashrc:/root/.bashrc
      - ./cfg/php/php.ini:/usr/local/etc/php/php.ini
      - ./cfg/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # - ./cfg/ImageMagick-policy.xml:/etc/ImageMagick-6/policy.xml #debian based only

  php73:
    hostname: php73
    container_name: php73
    image: "m0bua/php:7.3-fpm-alpine-dev"
    # restart: always
    volumes:
      - www:/var/www
      - ./cfg/d.bashrc:/root/.bashrc
      - ./cfg/php/php.ini:/usr/local/etc/php/php.ini
      - ./cfg/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # - ./cfg/ImageMagick-policy.xml:/etc/ImageMagick-6/policy.xml #debian based only

  php74:
    hostname: php74
    container_name: php74
    image: "m0bua/php:7.4-fpm-alpine-dev"
    # restart: always
    volumes:
      - ~/prj:/var/www
      - ./cfg/d.bashrc:/root/.bashrc
      - ./cfg/php/php.ini:/usr/local/etc/php/php.ini
      - ./cfg/php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      # - ./cfg/ImageMagick-policy.xml:/etc/ImageMagick-6/policy.xml #debian based only

  db:
    hostname: db
    container_name: db
    image: mariadb
    # image: mysql
    # image: mysql:8
    # image: mysql:5
    # restart: always
    command: 
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
      - --sql_mode=ONLY_FULL_GROUP_BY
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
      - ./cfg/d.bashrc:/root/.bashrc
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret

  dns:
    hostname: dns
    container_name: dns
    image: defreitas/dns-proxy-server
    # restart: always
    ports:
      # - 8053:5380
      - 53:53/udp
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/resolv.conf:/etc/resolv.conf
      - ./cfg/dns.json:/app/conf/config.json
      - ./cfg/d.bashrc:/root/.bashrc
  
  mail:
    hostname: mail
    container_name: mail
    image: mailhog/mailhog
    # restart: always

  adminer:
    hostname: adminer
    container_name: adminer
    image: adminer
    # restart: always

volumes:
  db:
  # mysql:
  # mysql8:
  # mysql5:
  www:
    driver: local
    driver_opts:
      type: none
      device: ~/prj
      o: bind
